version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html/
    ports:
      - 80:80
  database:
    image: mariadb
    volumes: 
      - ./song_game.sql:/docker-entrypoint-initdb.d/song_game.sql
    environment:
      MARIADB_ROOT_PASSWORD: wrjkn422
      MARIADB_DATABASE: song_game